"""add_knowledge_graph

Revision ID: 45d8e6b55231
Revises: 16a52b1aaeba
Create Date: 2026-09-09 14:29:27.916746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45d8e6b55231'
down_revision: Union[str, Sequence[str], None] = '16a52b1aaeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    op.create_table('knowledgenode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgenode_document_id'), 'knowledgenode', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledgenode_label'), 'knowledgenode', ['label'], unique=False)
    op.create_index(op.f('ix_knowledgenode_node_type'), 'knowledgenode', ['node_type'], unique=False)
    op.create_table('knowledgeedge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledgenode.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['knowledgenode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgeedge_source_id'), 'knowledgeedge', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledgeedge_target_id'), 'knowledgeedge', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledgeedge_target_id'), table_name='knowledgeedge')
    op.drop_index(op.f('ix_knowledgeedge_source_id'), table_name='knowledgeedge')
    op.drop_table('knowledgeedge')
    op.drop_index(op.f('ix_knowledgenode_node_type'), table_name='knowledgenode')
    op.drop_index(op.f('ix_knowledgenode_label'), table_name='knowledgenode')
    op.drop_index(op.f('ix_knowledgenode_document_id'), table_name='knowledgenode')
    op.drop_table('knowledgenode')
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
